<?php
//000000604800a:1:{i:0;a:14:{s:2:"id";s:4:"1574";s:5:"title";s:20:"助学金资助33333";s:8:"keywords";s:15:"助学金资助";s:11:"description";s:15:"助学金资助";s:7:"content";s:9174:"&lt;span style=&quot;white-space:normal;font-family:宋体;&quot;&gt;首先感谢大家对网站的信任，让我们逐步成为国内有影响力的平台之一。在工作中，我们偶尔会发现有一些&lt;/span&gt;&lt;span style=&quot;white-space:normal;font-family:宋体;&quot;&gt;极度困难&lt;/span&gt;&lt;span style=&quot;white-space:normal;font-family:宋体;&quot;&gt;的女孩，因为家庭的原因，缺少学费和基本的生活费，不能完成自己的学业，因此出来寻找&lt;/span&gt;&lt;a href=&quot;http://www.baidu.com/baidu?wd=%B0%FC%D1%F8&amp;amp;tn=monline_4_dg&quot; style=&quot;white-space:normal;&quot;&gt;&lt;u&gt;&lt;span style=&quot;font-family:宋体;&quot;&gt;包养&lt;/span&gt;&lt;/u&gt;&lt;/a&gt;&lt;span style=&quot;white-space:normal;font-family:宋体;&quot;&gt;，对于这种情况我们打算用&lt;/span&gt;&lt;span style=&quot;white-space:normal;&quot;&gt;“&lt;/span&gt;&lt;span style=&quot;white-space:normal;font-family:宋体;&quot;&gt;助学基金&lt;/span&gt;&lt;span style=&quot;white-space:normal;font-family:Tahoma;&quot;&gt;”&lt;/span&gt;&lt;span style=&quot;white-space:normal;font-family:宋体;&quot;&gt;的方式予以无偿帮助，避免那些身心尚未发育完全的女孩过早走上社会。&lt;/span&gt;&lt;br style=&quot;white-space:normal;&quot; /&gt;
&lt;span style=&quot;white-space:normal;font-family:宋体;&quot;&gt;一、对于需要&lt;/span&gt;&lt;span style=&quot;white-space:normal;&quot;&gt;“&lt;/span&gt;&lt;span style=&quot;white-space:normal;font-family:宋体;&quot;&gt;助学基金&lt;/span&gt;&lt;span style=&quot;white-space:normal;font-family:Tahoma;&quot;&gt;”&lt;/span&gt;&lt;span style=&quot;white-space:normal;font-family:宋体;&quot;&gt;的申请人：&lt;/span&gt;&lt;br style=&quot;white-space:normal;&quot; /&gt;
&lt;span style=&quot;white-space:normal;&quot;&gt;&amp;nbsp; &amp;nbsp;&amp;nbsp; &amp;nbsp;&amp;nbsp;&amp;nbsp;1&lt;/span&gt;&lt;span style=&quot;white-space:normal;font-family:宋体;&quot;&gt;）必须由本人亲自申请；&lt;/span&gt;&lt;br style=&quot;white-space:normal;&quot; /&gt;
&lt;span style=&quot;white-space:normal;&quot;&gt;&amp;nbsp; &amp;nbsp;&amp;nbsp; &amp;nbsp;&amp;nbsp;&amp;nbsp;2&lt;/span&gt;&lt;span style=&quot;white-space:normal;font-family:宋体;&quot;&gt;）申请人需要提供身份证明：&lt;/span&gt;&lt;br style=&quot;white-space:normal;&quot; /&gt;
&lt;span style=&quot;white-space:normal;&quot;&gt;&amp;nbsp; &amp;nbsp;&amp;nbsp; &amp;nbsp;&amp;nbsp; &amp;nbsp;&amp;nbsp; &amp;nbsp;&amp;nbsp; &amp;nbsp; a&lt;/span&gt;&lt;span style=&quot;white-space:normal;font-family:宋体;&quot;&gt;、身份证（正反面）或户口本（需要户头和申请人页）；&lt;/span&gt;&lt;br style=&quot;white-space:normal;&quot; /&gt;
&lt;span style=&quot;white-space:normal;&quot;&gt;&amp;nbsp; &amp;nbsp;&amp;nbsp; &amp;nbsp;&amp;nbsp; &amp;nbsp;&amp;nbsp; &amp;nbsp;&amp;nbsp; &amp;nbsp; b&lt;/span&gt;&lt;span style=&quot;white-space:normal;font-family:宋体;&quot;&gt;、学籍证明（盖有学校印章和本人照片的学生证或学校开具的证明文件）；&lt;/span&gt;&lt;br style=&quot;white-space:normal;&quot; /&gt;
&lt;span style=&quot;white-space:normal;&quot;&gt;&amp;nbsp; &amp;nbsp;&amp;nbsp; &amp;nbsp;&amp;nbsp; &amp;nbsp;&amp;nbsp; &amp;nbsp;&amp;nbsp; &amp;nbsp; c&lt;/span&gt;&lt;span style=&quot;white-space:normal;font-family:宋体;&quot;&gt;、上一学期的成绩报告单；&lt;/span&gt;&lt;br style=&quot;white-space:normal;&quot; /&gt;
&lt;span style=&quot;white-space:normal;&quot;&gt;&amp;nbsp; &amp;nbsp;&amp;nbsp; &amp;nbsp;&amp;nbsp; &amp;nbsp;&amp;nbsp; &amp;nbsp;&amp;nbsp; &amp;nbsp; d&lt;/span&gt;&lt;span style=&quot;white-space:normal;font-family:宋体;&quot;&gt;、上一学期的学费缴费证明和消费凭证；&lt;/span&gt;&lt;br style=&quot;white-space:normal;&quot; /&gt;
&lt;span style=&quot;white-space:normal;&quot;&gt;&amp;nbsp; &amp;nbsp;&amp;nbsp; &amp;nbsp;&amp;nbsp; &amp;nbsp;&amp;nbsp; &amp;nbsp;&amp;nbsp; &amp;nbsp; e&lt;/span&gt;&lt;span style=&quot;white-space:normal;font-family:宋体;&quot;&gt;、其它能证明本人身份和学籍信息的相关材料。&lt;/span&gt;&lt;br style=&quot;white-space:normal;&quot; /&gt;
&lt;span style=&quot;white-space:normal;&quot;&gt;&amp;nbsp; &amp;nbsp;&amp;nbsp; &amp;nbsp;&amp;nbsp;&amp;nbsp;3&lt;/span&gt;&lt;span style=&quot;white-space:normal;font-family:宋体;&quot;&gt;）申请人需要通过&lt;/span&gt;&lt;span style=&quot;white-space:normal;font-family:Tahoma;&quot;&gt;QQ&lt;/span&gt;&lt;span style=&quot;white-space:normal;font-family:宋体;&quot;&gt;视频进行真人验证，并接受简单的提问；&lt;/span&gt;&lt;br style=&quot;white-space:normal;&quot; /&gt;
&lt;span style=&quot;white-space:normal;&quot;&gt;&amp;nbsp; &amp;nbsp;&amp;nbsp; &amp;nbsp;&amp;nbsp;&amp;nbsp;4&lt;/span&gt;&lt;span style=&quot;white-space:normal;font-family:宋体;&quot;&gt;）以上事项办完之后，我们会验证信息的真实性，予以资助或拒绝申请；&lt;/span&gt;&lt;br style=&quot;white-space:normal;&quot; /&gt;
&lt;span style=&quot;white-space:normal;&quot;&gt;&amp;nbsp; &amp;nbsp;&amp;nbsp; &amp;nbsp;&amp;nbsp;&amp;nbsp;5&lt;/span&gt;&lt;span style=&quot;white-space:normal;font-family:宋体;&quot;&gt;）对于确认资助的，需提供本人名下的银行卡或户口簿上直系亲属名下的银行卡，我们会在通知之后，予以资助一个学期的学费和部分生活费，金额视当地平均标准；&lt;/span&gt;&lt;br style=&quot;white-space:normal;&quot; /&gt;
&lt;span style=&quot;white-space:normal;&quot;&gt;&amp;nbsp; &amp;nbsp;&amp;nbsp; &amp;nbsp;&amp;nbsp;&amp;nbsp;6&lt;/span&gt;&lt;span style=&quot;white-space:normal;font-family:宋体;&quot;&gt;）半年后，可以重复申请。&lt;/span&gt;&lt;br style=&quot;white-space:normal;&quot; /&gt;
&lt;span style=&quot;white-space:normal;font-family:宋体;&quot;&gt;二、对于赞助&lt;/span&gt;&lt;span style=&quot;white-space:normal;&quot;&gt;“&lt;/span&gt;&lt;span style=&quot;white-space:normal;font-family:宋体;&quot;&gt;助学基金&lt;/span&gt;&lt;span style=&quot;white-space:normal;font-family:Tahoma;&quot;&gt;”&lt;/span&gt;&lt;span style=&quot;white-space:normal;font-family:宋体;&quot;&gt;的爱心会员：&lt;/span&gt;&lt;br style=&quot;white-space:normal;&quot; /&gt;
&lt;span style=&quot;white-space:normal;&quot;&gt;&amp;nbsp; &amp;nbsp;&amp;nbsp; &amp;nbsp;&amp;nbsp;&amp;nbsp;1&lt;/span&gt;&lt;span style=&quot;white-space:normal;font-family:宋体;&quot;&gt;）资助金额以&lt;/span&gt;&lt;span style=&quot;white-space:normal;font-family:Tahoma;&quot;&gt;5000&lt;/span&gt;&lt;span style=&quot;white-space:normal;font-family:宋体;&quot;&gt;元为单位，上不封顶，主动申请，资助后不予退还；&lt;/span&gt;&lt;br style=&quot;white-space:normal;&quot; /&gt;
&lt;span style=&quot;white-space:normal;&quot;&gt;&amp;nbsp; &amp;nbsp;&amp;nbsp; &amp;nbsp;&amp;nbsp;&amp;nbsp;2&lt;/span&gt;&lt;span style=&quot;white-space:normal;font-family:宋体;&quot;&gt;）在专栏中对&lt;/span&gt;&lt;span style=&quot;white-space:normal;font-family:Tahoma;&quot;&gt;“&lt;/span&gt;&lt;span style=&quot;white-space:normal;font-family:宋体;&quot;&gt;爱心会员&lt;/span&gt;&lt;span style=&quot;white-space:normal;font-family:Tahoma;&quot;&gt;”&lt;/span&gt;&lt;span style=&quot;white-space:normal;font-family:宋体;&quot;&gt;进行个人情况予以表扬和推介；&lt;/span&gt;&lt;br style=&quot;white-space:normal;&quot; /&gt;
&lt;span style=&quot;white-space:normal;&quot;&gt;&amp;nbsp; &amp;nbsp;&amp;nbsp; &amp;nbsp;&amp;nbsp;&amp;nbsp;3&lt;/span&gt;&lt;span style=&quot;white-space:normal;font-family:宋体;&quot;&gt;）有权查阅爱心资助的项目和资金使用情况；&lt;/span&gt;&lt;br style=&quot;white-space:normal;&quot; /&gt;
&lt;span style=&quot;white-space:normal;&quot;&gt;&amp;nbsp; &amp;nbsp;&amp;nbsp; &amp;nbsp;&amp;nbsp;&amp;nbsp;4&lt;/span&gt;&lt;span style=&quot;white-space:normal;font-family:宋体;&quot;&gt;）优先推介对于想寻求事业上的发展的女孩给爱心会员（非&lt;/span&gt;&lt;a href=&quot;http://www.gzaio.com/&quot; style=&quot;white-space:normal;&quot;&gt;&lt;u&gt;&lt;span style=&quot;font-family:宋体;&quot;&gt;包养&lt;/span&gt;&lt;/u&gt;&lt;/a&gt;&lt;span style=&quot;white-space:normal;font-family:宋体;&quot;&gt;性质）。&lt;/span&gt;&lt;br style=&quot;white-space:normal;&quot; /&gt;
&lt;span style=&quot;white-space:normal;&quot;&gt;&amp;nbsp; &amp;nbsp;&amp;nbsp; &amp;nbsp;&amp;nbsp;&amp;nbsp;&lt;/span&gt;&lt;span style=&quot;white-space:normal;font-family:宋体;&quot;&gt;未尽事宜，请联系&lt;/span&gt;&lt;span style=&quot;white-space:normal;font-family:Tahoma;&quot;&gt;QQ&lt;/span&gt;&lt;span style=&quot;white-space:normal;font-family:宋体;&quot;&gt;：&lt;/span&gt;&lt;span style=&quot;white-space:normal;&quot;&gt;943400346&lt;/span&gt;&lt;span style=&quot;white-space:normal;font-family:宋体;&quot;&gt;，保留所有权利。&lt;/span&gt;&lt;span style=&quot;white-space:normal;&quot;&gt;&amp;nbsp;&lt;/span&gt;";s:6:"author";N;s:4:"hits";s:1:"0";s:11:"update_time";N;s:7:"addtime";s:19:"2017-05-25 09:54:37";s:6:"status";s:1:"0";s:4:"rank";s:1:"0";s:9:"recommend";s:1:"1";s:4:"type";s:1:"2";s:3:"pid";s:1:"1";}}
?>